# WRITTEN DECEMBER 3, 2024, BY J. JEHOVAHKIN
# FORKED FROM THE CODE I WROTE FOR MY KEYPAD TO FUNCTION, ITSELF FORKED FROM CODE FROM SOME WEBSITE SOMEWHERE
# THE HUNGER BURNS WITHIN MY GUT
import RPi.GPIO as GPIO
import time

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)

# ROWS
